openapi: 3.0.0
info:
  title: API de Carrito
  description: Documentación de la API para el módulo de carrito en el sistema de ecommerce.
  version: 1.0.0
paths:
  /api/carts:
    get:
      summary: Obtener todos los carritos
      responses:
        '200':
          description: Lista de carritos obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        '500':
          description: Error al obtener los carritos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Crear un nuevo carrito
      responses:
        '201':
          description: Carrito creado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error al crear el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por ID
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Carrito obtenido con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al obtener el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}/products/{pid}:
    post:
      summary: Agregar un producto al carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Producto agregado al carrito con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '403':
          description: Producto no puede ser agregado al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Carrito o producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al agregar el producto al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Eliminar un producto del carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito o producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al eliminar el producto del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}/products:
    put:
      summary: Actualizar el carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
      responses:
        '200':
          description: Carrito actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al actualizar el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}/products/{pid}/quantity:
    put:
      summary: Actualizar la cantidad de un producto en el carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Cantidad del producto actualizada en el carrito con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito o producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al actualizar la cantidad del producto en el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}/clear:
    delete:
      summary: Vaciar el carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Carrito vaciado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al vaciar el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/carts/{cid}/purchase:
    post:
      summary: Comprar los productos del carrito
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compra procesada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Error al procesar la compra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        # Otros campos del carrito pueden ser agregados aquí
    Error:
      type: object
      properties:
        message:
          type: string